"""Add version and active fields to Bill

Revision ID: 14ad38189cb0
Revises: 
Create Date: 2025-07-03 00:23:51.651025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ad38189cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_bill_congress_type_number'), type_='unique')
        batch_op.create_unique_constraint('uq_bill_congress_type_number_version', ['congress', 'bill_type', 'bill_number', 'version'])

    with op.batch_alter_table('bill_category_mapping', schema=None) as batch_op:
        batch_op.alter_column('section_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_category_mapping', schema=None) as batch_op:
        batch_op.alter_column('section_reference',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bill_congress_type_number_version', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_bill_congress_type_number'), ['congress', 'bill_type', 'bill_number'])
        batch_op.drop_column('active')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
