"""Add sneakiness_score to BillCategoryMapping

Revision ID: 7dfebb57eea7
Revises: 14ad38189cb0
Create Date: 2025-07-03 00:45:03.581852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfebb57eea7'
down_revision = '14ad38189cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_category_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sneakiness_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_category_mapping', schema=None) as batch_op:
        batch_op.drop_column('sneakiness_score')

    # ### end Alembic commands ###
