"""Add HiddenProvision table for storing detailed hidden provision analysis

Revision ID: bbd9e256d68a
Revises: d291c9c77bad
Create Date: 2025-07-12 11:33:49.390887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd9e256d68a'
down_revision = 'd291c9c77bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bill')
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bill_congress_type_number_version'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bill_congress_type_number_version'), ['congress', 'bill_type', 'bill_number', 'version'])

    op.create_table('_alembic_tmp_bill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('congress', sa.INTEGER(), nullable=False),
    sa.Column('bill_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('bill_number', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('introduced_date', sa.DATETIME(), nullable=True),
    sa.Column('last_action_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sponsor_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sponsor_party', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sponsor_state', sa.VARCHAR(length=5), nullable=True),
    sa.Column('congress_api_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('ai_analysis', sa.TEXT(), nullable=True),
    sa.Column('policy_categories', sa.TEXT(), nullable=True),
    sa.Column('stakeholder_analysis', sa.TEXT(), nullable=True),
    sa.Column('complexity_score', sa.FLOAT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
