"""Add display_ready field to Bill model

Revision ID: c8a785650162
Revises: bbd9e256d68a
Create Date: 2025-07-12 16:39:22.361270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a785650162'
down_revision = 'bbd9e256d68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable with default
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_ready', sa.Boolean(), nullable=True, default=False))
    
    # Update all existing rows to have False
    op.execute("UPDATE bill SET display_ready = 0 WHERE display_ready IS NULL")
    
    # Then make it non-nullable
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.alter_column('display_ready', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('display_ready')

    # ### end Alembic commands ###
