"""Add unique constraint to bills table

Revision ID: f4329a90661a
Revises: 
Create Date: 2025-06-27 16:13:08.084499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4329a90661a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bill_congress_type_number', ['congress', 'bill_type', 'bill_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bill_congress_type_number', type_='unique')

    # ### end Alembic commands ###
