FEDERAL_POLICY_CATEGORIES = [
  "Agriculture and Food",
  "Arts and Culture",
  "Budget and Fiscal Policy",
  "Civil Rights and Liberties",
  "Commerce and Trade",
  "Communications and Technology",
  "Consumer Protection",
  "Criminal Justice and Law Enforcement",
  "Defense and National Security",
  "Disaster Relief and Emergency Management",
  "Economic Development",
  "Education",
  "Elections and Campaign Finance",
  "Energy",
  "Environment and Natural Resources",
  "Ethics and Government Reform",
  "Financial Services and Banking",
  "Foreign Affairs and Diplomacy",
  "Government Operations",
  "Health Care",
  "Housing and Urban Development",
  "Immigration",
  "Intelligence and Surveillance",
  "International Trade",
  "Labor and Employment",
  "Native American Affairs",
  "Postal Service",
  "Public Lands and Natural Resources",
  "Science and Space",
  "Social Security",
  "Social Services and Welfare",
  "Taxation",
  "Transportation",
  "Veterans Affairs",
  "Water Resources"
]